#include "pid.h"
#include <limits.h>
static int64_t cl(int64_t x,int64_t a,int64_t b){return x<a?a:(x>b?b:x);}
static int32_t qi(int64_t x){int64_t y=x>=0?(x+32768)/65536:(x-32768)/65536;return y>INT32_MAX?INT32_MAX:(y<INT32_MIN?INT32_MIN:(int32_t)y);}
static bool calc(PID_Controller*p){int64_t k=((int64_t)p->config.kiQ16PerSecond*p->config.samplePeriodUs+(p->config.kiQ16PerSecond>=0?500000:-500000))/1000000;int64_t d=((int64_t)p->config.kdQ16Second*1000000+(p->config.kdQ16Second>=0?p->config.samplePeriodUs/2:-(int64_t)p->config.samplePeriodUs/2))/p->config.samplePeriodUs;if(k>INT32_MAX||k<INT32_MIN||d>INT32_MAX||d<INT32_MIN)return false;p->kiStepQ16=(int32_t)k;p->kdStepQ16=(int32_t)d;return true;}
static bool valid(const PID_Config*c){return c&&c->samplePeriodUs&&c->samplePeriodUs<=10000000U&&c->outputMin<c->outputMax&&c->integratorMin<=c->integratorMax&&c->deadband>=0&&c->derivativeFilterQ15<=32768U&&c->action<=PI_ACTION_REVERSE&&c->antiWindup<=PI_ANTI_WINDUP_BACK_CALCULATION;}
bool PID_init(PID_Controller*p,const PID_Config*c){if(!p||!valid(c))return false;p->config=*c;if(!calc(p))return false;p->integratorQ16=0;p->derivativeQ16=0;p->previousOutput=c->outputMin;p->automatic=true;p->initialized=true;p->hasPrevious=false;return true;}
bool PID_reset(PID_Controller*p,int32_t o){if(!p||!p->initialized)return false;p->integratorQ16=0;p->derivativeQ16=0;p->previousOutput=(int32_t)cl(o,p->config.outputMin,p->config.outputMax);p->hasPrevious=false;return true;}
bool PID_setManualMode(PID_Controller*p,int32_t o){if(!p||!p->initialized)return false;p->automatic=false;p->previousOutput=(int32_t)cl(o,p->config.outputMin,p->config.outputMax);return true;}
bool PID_setAutomaticMode(PID_Controller*p,int32_t sp,int32_t m){if(!p||!p->initialized)return false;int64_t e=(int64_t)sp-m;if(p->config.action==PI_ACTION_REVERSE)e=-e;if(e<p->config.deadband&&e>-p->config.deadband)e=0;int64_t prop=(int64_t)p->config.kpQ16*e;p->integratorQ16=cl(((int64_t)p->previousOutput-p->config.feedForward)*65536-prop,(int64_t)p->config.integratorMin*65536,(int64_t)p->config.integratorMax*65536);p->automatic=true;p->hasPrevious=false;return true;}
bool PID_setTunings(PID_Controller*p,int32_t kp,int32_t ki,int32_t kd){if(!p||!p->initialized)return false;p->config.kpQ16=kp;p->config.kiQ16PerSecond=ki;p->config.kdQ16Second=kd;return calc(p);}
bool PID_setSamplePeriod(PID_Controller*p,uint32_t us){if(!p||!p->initialized||!us||us>10000000U)return false;p->config.samplePeriodUs=us;return calc(p);}
bool PID_setOutputLimits(PID_Controller*p,int32_t a,int32_t b){if(!p||!p->initialized||a>=b)return false;p->config.outputMin=a;p->config.outputMax=b;p->previousOutput=(int32_t)cl(p->previousOutput,a,b);return true;}
bool PID_setIntegratorLimits(PID_Controller*p,int32_t a,int32_t b){if(!p||!p->initialized||a>b)return false;p->config.integratorMin=a;p->config.integratorMax=b;p->integratorQ16=cl(p->integratorQ16,(int64_t)a*65536,(int64_t)b*65536);return true;}
bool PID_setDerivativeMode(PID_Controller*p,bool m){if(!p||!p->initialized)return false;p->config.derivativeOnMeasurement=m;p->hasPrevious=false;return true;}
bool PID_setDerivativeFilter(PID_Controller*p,uint16_t f){if(!p||!p->initialized||f>32768U)return false;p->config.derivativeFilterQ15=f;return true;}
bool PID_setFeedForward(PID_Controller*p,int32_t f){if(!p||!p->initialized)return false;p->config.feedForward=f;return true;}
bool PID_setDeadband(PID_Controller*p,int32_t d){if(!p||!p->initialized||d<0)return false;p->config.deadband=d;return true;}
bool PID_setSlewLimits(PID_Controller*p,uint32_t r,uint32_t f){if(!p||!p->initialized||r>INT32_MAX||f>INT32_MAX)return false;p->config.outputRiseLimit=r;p->config.outputFallLimit=f;return true;}
bool PID_update(PID_Controller*p,int32_t sp,int32_t m,PID_Result*r){if(!p||!p->initialized)return false;PID_Result z={0};if(!r)r=&z;r->setpoint=sp;r->measurement=m;r->automatic=p->automatic;r->valid=true;if(!p->automatic){r->output=p->previousOutput;r->integral=qi(p->integratorQ16);return true;}int64_t e=(int64_t)sp-m;if(p->config.action==PI_ACTION_REVERSE)e=-e;int32_t ei=(int32_t)cl(e,INT32_MIN,INT32_MAX);int32_t ee=(e<p->config.deadband&&e>-p->config.deadband)?0:ei;r->error=ei;r->effectiveError=ee;int64_t prop=(int64_t)p->config.kpQ16*ee;int64_t dErr=0;if(p->hasPrevious)dErr=p->config.derivativeOnMeasurement?((int64_t)m-p->previousMeasurement)*(p->config.action==PI_ACTION_REVERSE?1:-1):(int64_t)ee-p->previousError;int64_t rawD=(int64_t)p->kdStepQ16*dErr;uint16_t a=p->config.derivativeFilterQ15;if(a==0U)p->derivativeQ16=rawD;else p->derivativeQ16+=((int64_t)a*(rawD-p->derivativeQ16))/32768;r->derivative=qi(p->derivativeQ16);int64_t oldI=p->integratorQ16,delta=(int64_t)p->kiStepQ16*ee,cand=cl(oldI+delta,(int64_t)p->config.integratorMin*65536,(int64_t)p->config.integratorMax*65536);int64_t uq=prop+cand+p->derivativeQ16+(int64_t)p->config.feedForward*65536;int32_t un=qi(uq),lim=(int32_t)cl(un,p->config.outputMin,p->config.outputMax);if(p->config.antiWindup==PI_ANTI_WINDUP_CONDITIONAL&&lim!=un){bool push=(un>p->config.outputMax&&delta>0)||(un<p->config.outputMin&&delta<0);if(push){cand=oldI;uq=prop+cand+p->derivativeQ16+(int64_t)p->config.feedForward*65536;un=qi(uq);lim=(int32_t)cl(un,p->config.outputMin,p->config.outputMax);}}int32_t out=lim;bool slew=false;if(p->config.outputRiseLimit&&(int64_t)out>(int64_t)p->previousOutput+p->config.outputRiseLimit){out=(int32_t)((int64_t)p->previousOutput+p->config.outputRiseLimit);slew=true;}if(p->config.outputFallLimit&&(int64_t)out<(int64_t)p->previousOutput-p->config.outputFallLimit){out=(int32_t)((int64_t)p->previousOutput-p->config.outputFallLimit);slew=true;}if(p->config.antiWindup==PI_ANTI_WINDUP_BACK_CALCULATION)cand+=(int64_t)(out-un)*p->config.backCalculationGainQ16;p->integratorQ16=cl(cand,(int64_t)p->config.integratorMin*65536,(int64_t)p->config.integratorMax*65536);p->previousOutput=out;p->previousMeasurement=m;p->previousError=ee;p->hasPrevious=true;r->proportional=qi(prop);r->integral=qi(p->integratorQ16);r->feedForward=p->config.feedForward;r->unclampedOutput=un;r->output=out;r->outputLimited=lim!=un;r->slewLimited=slew;r->integratorLimited=p->integratorQ16!=oldI+delta;return true;}
int32_t PID_getOutput(const PID_Controller*p){return p&&p->initialized?p->previousOutput:0;}int32_t PID_getIntegrator(const PID_Controller*p){return p&&p->initialized?qi(p->integratorQ16):0;}bool PID_isAutomatic(const PID_Controller*p){return p&&p->initialized&&p->automatic;}
