#ifndef BSP_BOARD_PINS_H_
#define BSP_BOARD_PINS_H_

#include "ti_msp_dl_config.h"

/* PB0..PB15 form one contiguous 16-bit LCD data bus. */
#define BOARD_LCD_DATA_PORT       LCD_DATA_PORT
#define BOARD_LCD_DATA_MASK       (0x0000FFFFUL)

/* LCD control signals generated by the LCD_CTRL SysConfig instance. */
#define BOARD_LCD_CTRL_PORT       LCD_CTRL_PORT
#define BOARD_LCD_WR_PIN          LCD_CTRL_WR_PIN
#define BOARD_LCD_RD_PIN          LCD_CTRL_RD_PIN
#define BOARD_LCD_CS_PIN          LCD_CTRL_CS_PIN
#define BOARD_LCD_RS_PIN          LCD_CTRL_RS_PIN
#define BOARD_LCD_RST_PIN         LCD_CTRL_RST_PIN
#define BOARD_LCD_BL_PIN          LCD_CTRL_BL_PIN

#endif
